name: Test Matrix

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-matrix:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18', '20']
        project: ['backend', 'frontend']

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: warranty_it_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package.json

      - name: Install dependencies
        working-directory: ./${{ matrix.project }}
        run: npm ci

      - name: Run linting
        working-directory: ./${{ matrix.project }}
        run: npm run lint

      - name: Run tests
        working-directory: ./${{ matrix.project }}
        run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/warranty_it_test
          JWT_SECRET: test-secret-key
          NODE_ENV: test

      - name: Run type check (frontend only)
        if: matrix.project == 'frontend'
        working-directory: ./${{ matrix.project }}
        run: npm run type-check
